In [14]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from subprocess import check_output
print(check_output(["ls", "twitter_data/"]).decode("utf8"))

training.1600000.processed.noemoticon.csv
training.1600000.processed.noemoticon.csv.zip



In [31]:
twitter_data_path = "twitter_data/training.1600000.processed.noemoticon.csv"

In [32]:
tw_data_df = pd.read_csv(twitter_data_path, engine='python', header=None)

In [33]:
tw_data_df.head()

0           1                             2         3                4  \
0  0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  _TheSpecialOne_   
1  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY    scotthamilton   
2  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY         mattycus   
3  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          ElleCTF   
4  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY           Karoli   

                                                   5  
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1  is upset that he can't update his Facebook by ...  
2  @Kenichan I dived many times for the ball. Man...  
3    my whole body feels itchy and like its on fire   
4  @nationwideclass no, it's not behaving at all....

## Spliting Train and Test data

In [34]:
print("Negative Count:", len(tw_data_df[tw_data_df[0]==4]))
print("Positive Count:", len(tw_data_df[tw_data_df[0]==0]))

Negative Count: 800000
Positive Count: 800000


In [35]:
X_train_df, X_test_df, y_train, y_test = train_test_split(tw_data_df, tw_data_df[[0]], test_size=0.3)

In [36]:
print("Train Negative Count:", len(X_train_df[X_train_df[0]==4]))
print("Train Positive Count:", len(X_train_df[X_train_df[0]==0]))

Train Negative Count: 560137
Train Positive Count: 559863


In [37]:
print("Test Negative Count:", len(X_test_df[X_test_df[0]==4]))
print("Test Positive Count:", len(X_test_df[X_test_df[0]==0]))

Test Negative Count: 239863
Test Positive Count: 240137


## Save Splited Train & Test to CSV

In [55]:
twitter_train_data_path = "twitter_data/training.csv"
twitter_test_data_path = "twitter_data/testing.csv"

In [56]:
X_train_df.to_csv(twitter_train_data_path, header=None, index=False)
X_test_df.to_csv(twitter_test_data_path, header=None, index=False)

## Checking

In [57]:
loaded_train_df = pd.read_csv(twitter_train_data_path, engine='python', header=None)
loaded_test_df = pd.read_csv(twitter_test_data_path, engine='python', header=None)

In [58]:
loaded_train_df.head()

0           1                             2         3               4  \
0  4  1793776320  Thu May 14 03:57:15 PDT 2009  NO_QUERY          foozzy   
1  4  1991549874  Mon Jun 01 07:14:28 PDT 2009  NO_QUERY         12Jansi   
2  0  1833914530  Mon May 18 00:55:25 PDT 2009  NO_QUERY  Jimmy_Saunders   
3  0  1966305086  Fri May 29 17:31:16 PDT 2009  NO_QUERY          Yo_lin   
4  4  1984814005  Sun May 31 15:51:41 PDT 2009  NO_QUERY     mmoorejones   

                                                   5  
0  work to take some more pix, school, sushi?, th...  
1  @dagira_tweets: Just to say a 'Hi' to Dave's c...  
2             @bswain Oh yeah, Mondays are the best   
3  follow friday.. follow me coz i only have 26 f...  
4     Getting iPhone today  Then movie with friends!

In [59]:
loaded_test_df.head()

0           1                             2         3                4  \
0  4  1834009132  Mon May 18 01:16:44 PDT 2009  NO_QUERY       Pete_Hyena   
1  0  2058782290  Sat Jun 06 15:37:01 PDT 2009  NO_QUERY   serioussarcasm   
2  0  2261930956  Sat Jun 20 21:35:32 PDT 2009  NO_QUERY  nowthatsasandra   
3  0  2061819960  Sat Jun 06 21:41:19 PDT 2009  NO_QUERY    beautifulcity   
4  0  1678243705  Sat May 02 06:02:51 PDT 2009  NO_QUERY     geminilady75   

                                                   5  
0  uguigkuygffjhfhjfhj is about how i feel today....  
1  My voice is so tired from singing..i'm gonna k...  
2           sad part  im not going to cry.... tears*  
3  WHY ARE DRUNKS SO LOUD. stupid dock right next...  
4              @MariaBeckett Sorry to hear that hun

In [66]:
print(np.zeros([3, 4]))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
